### ISSUE TITLE
Verification of correct types/classes ?

### ISSUE THREAD

**Issue by akuckartz** [LOD-Laundromat/LOD-Laundromat#4]
There are 0 warnings here:
http://lodlaundromat.org/resource/334ad286bc14a4e7244570e04243c4f8

But the property `dc:license` of the "cleaned" (and the "dirty") data has a literal value "cc-by" instead of a link to a http://purl.org/dc/terms/LicenseDocument as required by http://dublincore.org/documents/dcmi-terms/#terms-license

**Comment by wouterbeek** [comment]
Very good point @akuckartz!

Unfortunately the LOD Laundromat does not check for clean semantics (yet). This would be a very nice extension, either as part of the LOD Laundromat architecture or as an application built on top of the LOD Laundromat.

Would you be aware of a reasoner that implements RDF(S) semantics correctly and exhibits a relatively low hardware footprint (since we must run it for 600,000+ data files)?

**Comment by akuckartz** [comment]
> Would you be aware of a reasoner that implements RDF(S) semantics correctly and exhibits a relatively low hardware footprint (since we must run it for 600,000+ data files)?

@wouterbeek Good question, but unfortunately I have no basis for making such a recommendation.

**Comment by akuckartz** [comment]
@wouterbeek Can RDFunit (http://aksw.org/Projects/RDFUnit.html) be used? http://rdfunit.aksw.org/demo/ even found errors in the small sample that I had not noticed!

**Comment by wouterbeek** [comment]
Sorry @akuckartz, I never took the time to look into your suggestion.  I'm closing this otherwise useful issue now.
